# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' parse GT of a VCF file into tables in R
#'
#' @param vcffile path to the VCF file with index
#' @param region  region to extract 
#' @param samples samples to extract
#' @return A list of genotypes and other fixed fields in VCF
#' @export
tableGT <- function(vcffile, region, samples = "-") {
    .Call('_vcfppR_tableGT', PACKAGE = 'vcfppR', vcffile, region, samples)
}

#' parse GL of a VCF file into tables in R
#'
#' @param vcffile path to the VCF file with index
#' @param region  region to extract 
#' @param samples samples to extract
#' @return A list of genotypes and other fixed fields in VCF
#' @export
tableGL <- function(vcffile, region, samples = "-") {
    .Call('_vcfppR_tableGL', PACKAGE = 'vcfppR', vcffile, region, samples)
}

#' parse PL of a VCF file into tables in R
#'
#' @param vcffile path to the VCF file with index
#' @param region  region to extract 
#' @param samples samples to extract
#' @return A list of genotypes and other fixed fields in VCF
#' @export
tablePL <- function(vcffile, region, samples = "-") {
    .Call('_vcfppR_tablePL', PACKAGE = 'vcfppR', vcffile, region, samples)
}

