# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get DS (dosage) of each sample and skip variants given a INFO tag of Float type and a cutoff
#' @param cutoff  skip variants with tag value smaller than this cutoff
#' @param tag     tag exists in INFO column
#' @param vcffile path to the VCF file with index
#' @param region  region to extract
#' @param samples samples to extract
#' @return A list of genotype dosages for each sample along with variant information in VCF
#' @export
getDSskipInfoTagFloat <- function(cutoff, tag, vcffile, region = "", samples = "-") {
    .Call(`_vcfppR_getDSskipInfoTagFloat`, cutoff, tag, vcffile, region, samples)
}

#' calculate the number of heterozygous SNPs for each sample
#' @param vcffile path to the VCF file with index
#' @param region  region to extract, default "" for all
#' @param pass restrict to variants with FILTER==PASS
#' @param qual restrict to variants with QUAL > qual.
#' @param samples samples to extract, default "-" for all
#' @return A list of heterozygosity couts for each sample along with its id in the vcf header
#' @export
heterozygosity <- function(vcffile, region = "", samples = "-", pass = FALSE, qual = 0) {
    .Call(`_vcfppR_heterozygosity`, vcffile, region, samples, pass, qual)
}

tableGT <- function(vcffile, region, samples = "-", qualval = 0, pass = FALSE, INFO = TRUE, snps = FALSE, indels = FALSE, multiallelics = FALSE, multisnps = FALSE) {
    .Call(`_vcfppR_tableGT`, vcffile, region, samples, qualval, pass, INFO, snps, indels, multiallelics, multisnps)
}

tableOther <- function(format, vcffile, region, samples = "-", qualval = 0, pass = FALSE, INFO = TRUE, snps = FALSE, indels = FALSE, multiallelics = FALSE, multisnps = FALSE) {
    .Call(`_vcfppR_tableOther`, format, vcffile, region, samples, qualval, pass, INFO, snps, indels, multiallelics, multisnps)
}

summaryVariants <- function(vcffile, region = "", samples = "-", filter_pass = FALSE, qual = 0) {
    .Call(`_vcfppR_summaryVariants`, vcffile, region, samples, filter_pass, qual)
}

summarySVs <- function(vcffile, region = "", samples = "-", filter_pass = FALSE, qual = 0) {
    .Call(`_vcfppR_summarySVs`, vcffile, region, samples, filter_pass, qual)
}

